### ISSUE TITLE
enhancement: [name].txt -> tree

### ISSUE THREAD

**Issue by Jamesbarford** [kepler471/listty#7]
Convert a "formatted" `.txt` file to tree

**Comment by kepler471** [comment]
am  on this, I have a couple implementations to try

**Comment by kepler471** [comment]
#10 This works smoothly. 

Uses a search method that looks for the required depth, and splits the lines into subgroups, headed by any child at that depth. This method avoids having to handle unindentations, or any backtracking, which were required for when the function was checking the string slice line by line. 

Additionally,  made a very important fix to the item type in [list.go](https://github.com/kepler471/listty/blob/adf3e2c63e18ecbbf1951c026e0cd1b5ae777ffa/list.go#L12). `item.Tail` was of type `[]item`, which meant that the state of any tail past the first depth was being lost. Now `item.Tail` is `[]*item`. This fix should solve errors that were seen when adding children or indenting items.
